### ISSUE TITLE
Variable undefined

### ISSUE THREAD

**Issue by CodeParrot** [reknih/informant-wp#2]
Line 145 in scheduleAgent.cs:  var t is not defined

**Comment by reknih** [comment]
Replace t.Name with "informatservice". Will this work?

**Comment by CodeParrot** [comment]
no, it does not. There is no such variable.

**Comment by reknih** [comment]
I mean as a string literal, in double quotes, hard coded, you know?

**Comment by CodeParrot** [comment]
Fixed it with the Task as global variable
